###
# Simply performs an echo
##

---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: latest

inputs:
  - name: tasks

outputs:
  - name: {{file}}

params:
  message:
  file: foo.txt

run:
  path: tasks/pipelines/04_tasking/tasks/create-file/task.sh

# tasking.echo
