###
# Introduces parameters set from another yaml file
##

jobs:
- name: print
  plan:
  - task: echo
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args:
          - {{message}}

# parameters
