---

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/mcarey-solstice/concourse-demo.git
    branch: master

jobs:
- name: tasks-example
  plan:
  - get: source-code
  - task: echo-hello-world
    file: source-code/pipelines/04_tasks/tasks/echo.yml
    params:
      message: Hello world
