###
# Copy this file as `.params.yml` and fill in the values
##

# Github configurations
git_original_uri:
git_original_private_key:
git_original_branch: master

git_mirror_uri:
git_mirror_private_key:
git_mirror_branch: master

# parameters
