###
#
##

resources:
- name: original
  type: git
  source:
    uri: {{git_original_uri}}
    branch: {{git_original_branch}}
    private_key: {{git_original_private_key}}
- name: mirror
  type: git
  source:
    uri: {{git_mirror_uri}}
    branch: {{git_mirror_branch}}
    private_key: {{git_mirror_private_key}}
- name: schedule
  type: time
  source:
    interval: 10m

jobs:
  - name: Synchronize fork
    plan:
      - aggregate:
          - get: schedule
            trigger: true
      - get: original
      - put: mirror
        params:
          repository: original
